# Generated by Django 4.1.5 on 2023-10-28 22:17

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=usuarios.models.custom_file_name)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_identificacion', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC'), ('CEDULA Extranjera', 'CEDULA Extranjera')], max_length=50)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('correo', models.BooleanField(default=False)),
            ],
        ),
    ]
