# Generated by Django 4.1.5 on 2023-10-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.CharField(default='Cali', max_length=50),
        ),
    ]
