apiVersion: apps/v1
kind: Deployment
metadata:
  name: tu-aplicacion-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tu-aplicacion2
  template:
    metadata:
      labels:
        app: tu-aplicacion2
    spec:
      containers:
      - name: tu-aplicacion2
        image: kpao74/login:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: production
        - name: MONGO_URI
          value: "mongodb+srv://rivaslina:rQbnSMvYNaSey0Ia@lawatty.rtzdvdd.mongodb.net/tickify?retryWrites=true&w=majority"