apiVersion: v1
kind: Service
metadata:
  name: tu-aplicacion-service2
spec:
  selector:
    app: tu-aplicacion2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
