# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: perfil
  template:
    metadata:
      labels:
        app: perfil
    spec:
      containers:
      - name: perfil
        image: kpao74/login:latest
        ports:
        - containerPort: 8000
